name: Pugna
version: 1.0
description: >
  Creates a fully featured PvP system
author: Tritania
website: https://github.com/tritania/Pugna

main: org.tritania.pugna.Pugna

commands:
  pg:
    description: Gives access to all pugna commands
    aliases: []
    usage: /<command> [argument]
  bounty:
    description: Allows you to place a bounty on a player (items go into escrow)
    aliases: []
    usage: /<command> [playername] [item] [amount]
  board:
    description: Allows you to access the scoreboard related commands
    aliases: []
    usage: /<command> [remove]
  dchest:
    description: Allows you to access death chest related commands
    aliases: []
    usage: /<command> [give] | [destroy] [all] 
  team:
    description: Allows you to access team related commands
    aliases: []
    usage: /<command>  
  t:
    description: Allows you to access team chat
    aliases: []
    usage: /<message>  
